spring:
  config:
    activate:
      on-profile: actuator
  boot:
    admin:
      client:
        url: http://localhost:8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - configprops
          - env
          - info
          - logfile
          - loggers
          - metrics
          - caches
          - flyway
          - liquibase
          - jolokia
