app:
  jwt:
    secret: zxcbzxhczhjxchzchjzgxhjcgzhxjcghjzx87498378237498273497JKHKJHKJHJKHKHjhbjbbbjkdbkbsdkbakbkbaskbdjasdsakjhdksabdbaskbdabdbadkhbashbdbhash8328943274792348723897423dhajkhdsjkdhjkhaskhjd38239472jkdsjksa

spring:
  config:
    activate:
      on-profile: security
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

security:
  basic:
    enabled: true
